[WIP]schema manager: support table metadata
arana-db/arana pull request #116
Opened 2022-04-03 18:07 UTC by Mulavar

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-04-04 09:23 UTC, AlexStocks commented on pkg/proto/schema_manager/loader.go
> +package schema_manager
路径和 package 名称 取名 schema 就可以了吧？

2022-04-04 13:28 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +	}
How about use `if columnMetaDataMap != nil {...}` instead? I think the `indexMetadataMap` is nil by default already.

2022-04-04 13:31 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +	resultSet, _, err := db.Call(context.Background(), getTableMetaDataSQL(tables))
Add context, same as above.

2022-04-04 13:37 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +		result[tableName] = columnMetadataList
Use result[tableName] = append(result[tableName], ColumnMetadata{...}) instead.

2022-04-04 13:38 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +		result[tableName] = indexMetadataList
Same as above.

2022-04-04 13:39 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +	return fmt.Sprintf(IndexMetaDataSQL, strings.Join(tableParamList, ","))
Use `strings.Builder` instead.

2022-04-04 13:39 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +	return fmt.Sprintf(TableMetaDataSQLInTables, strings.Join(tableParamList, ","))
Same as above.

2022-04-04 13:45 UTC, jjeffcaii commented on pkg/proto/schema_manager/loader.go
> +	IndexMetaDataSQL         = "SELECT TABLE_NAME, INDEX_NAME FROM information_schema.statistics WHERE TABLE_NAME IN (%s)"
Is it necessary to export these SQL template string?

2022-04-04 13:47 UTC, jjeffcaii requested changes
pls fix

2022-04-04 13:49 UTC, jjeffcaii commented
PS: add license for each source file.

2022-04-06 03:34 UTC, Mulavar commented on pkg/proto/schema_manager/loader.go
> +package schema_manager
更合适的命名我还没想好，这里不用 schema 的原因是，schema 一般在 mysql 里和 database 是同个意思，arana 里一般传参也用 schema 去指代要查的目标数据库，所以我觉得这里取名 schema 会有一点歧义，这块我会更关注下，等开发完毕再商量个更合适的包名？

2022-04-06 16:46 UTC, Mulavar commented
目前仍需完成的点：
1. 在 where 条件里增加 table_schema，要改写成成 preparedstatement 的形式；
2. 抽取一个如 SchemaManager 的接口；
3. 接入到 optimizer 流程里；
4. 联调 select *。

2022-04-07 02:18 UTC, jjeffcaii approved these changes

2022-04-16 13:26 UTC, dongzl approved these changes

2022-04-17 08:39 UTC, AlexStocks approved these changes

2022-04-17 08:40 UTC, AlexStocks commented on pkg/proto/schema_manager/loader.go
> +			StmtNode:    stmtNode,
讲道理，你这个 stmt 赋值，就 stmtNode 有意义，其他的都是默认值，没必要写的

2022-04-18 05:30 UTC, Lvnszn commented on pkg/proto/metadata.go
> +type ColumnMetadata struct {
这边的 Metadata 是小写的，下面的MetaData是大写的D，是有啥区别不？

2022-04-18 05:33 UTC, Lvnszn commented on pkg/proto/schema_manager/loader.go
> +	}
一般来讲先判断他不为空的返回会更好一点

2022-04-18 05:38 UTC, Lvnszn approved these changes

2022-04-19 00:59 UTC, merged