feat: add show tables
arana-db/arana pull request #146
Opened 2022-04-23 16:35 UTC by georgehao

**What this PR does**:
show tables

**Which issue(s) this PR fixes**:

Fixes #77

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-04-25 11:07 UTC, AlexStocks approved these changes

2022-04-26 02:43 UTC, dongzl requested changes

2022-04-26 03:07 UTC, dongzl approved these changes

2022-04-29 02:33 UTC, jjeffcaii approved these changes
Please add unit tests, thanks~

2022-04-29 04:02 UTC, merged