fix: #228
arana-db/arana pull request #232
Opened 2022-06-18 10:06 UTC by Penglq

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-06-18 10:23 UTC, dongzl requested changes

2022-06-18 10:23 UTC, dongzl commented on pkg/runtime/plan/show_tables.go
> +	rcontext "github.com/arana-db/arana/pkg/runtime/context"
format import.

2022-06-18 10:23 UTC, dongzl commented on pkg/runtime/plan/show_tables.go
> +	cMysql "github.com/arana-db/arana/pkg/constants/mysql"
`cMysql` is not a good name, how about `constant` directly?

2022-06-18 11:36 UTC, dongzl approved these changes

2022-06-18 13:41 UTC, jjeffcaii approved these changes
LGTM

2022-06-18 15:40 UTC, Lvnszn approved these changes

2022-06-19 00:22 UTC, AlexStocks approved these changes

2022-06-19 00:22 UTC, merged