optimize maxAllowedPacket config fix: #292 #281
arana-db/arana pull request #297
Opened 2022-07-16 15:55 UTC by Penglq

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #292 #281 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-07-17 12:45 UTC, georgehao commented on pkg/config/model.go
> +	"golang.org/x/text/cases"
format import

2022-07-17 12:46 UTC, georgehao commented on pkg/boot/discovery.go
> +		return nil, nil
maybe need return a err?

2022-07-17 12:51 UTC, georgehao commented on pkg/config/model.go
> +func (pm *ParametersMap) Case2Camel(name string) string {
rename the func name. how about CamelCase() ?

2022-07-17 13:03 UTC, georgehao commented on pkg/config/model.go
> +	}
```go
return string(unicode.ToLower(str[0])) + str[1:])
```

2022-07-17 13:03 UTC, georgehao commented on pkg/mysql/client.go
> +	"github.com/arana-db/arana/pkg/constants"
format code

2022-07-17 13:03 UTC, georgehao commented on pkg/mysql/client.go
> +// Note: In a future iteration this should be abolished and merged into to Execute API.
// Note: In a future iteration this should be abolished and merged into the Executed API.

maybe this ?

2022-07-17 13:07 UTC, dongzl requested changes

2022-07-17 13:07 UTC, dongzl commented on pkg/boot/discovery.go
> +	GetClusterObject(ctx context.Context, cluster string) (*config.DataSourceCluster, error)
Suggest rename the method, `GetClusterObject`  is confused with `GetCluster`.

`GetDataSourceCluster `  directly  or  other.

2022-07-17 13:07 UTC, dongzl commented on pkg/boot/boot.go
> +		clusterObjects *config.DataSourceCluster
Suggest  named `cluster`.

2022-07-17 13:07 UTC, dongzl commented on pkg/mysql/client.go
> +	"github.com/arana-db/arana/pkg/constants"
format import.

2022-07-19 03:12 UTC, jjeffcaii commented on pkg/runtime/optimize/optimizer.go
> +
reformat imports

2022-07-19 03:12 UTC, jjeffcaii approved these changes
LGTM

2022-07-19 07:42 UTC, dongzl requested changes

2022-07-19 07:42 UTC, dongzl commented on pkg/config/model.go
> +func (pm *ParametersMap) LowercaseFirstLetter(str string) string {
Suggest `LowerCase`.

2022-07-23 14:21 UTC, georgehao approved these changes

2022-07-23 23:33 UTC, merged