[SQL] Support SHOW CHARACTER SET Statement
arana-db/arana pull request #396
Opened 2022-09-03 05:54 UTC by robbinhan

**What this PR does**:
Support SHOW CHARACTER SET Statement

**Which issue(s) this PR fixes**:
Fixes #388 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-09-03 08:45 UTC, dongzl requested changes

2022-09-03 08:45 UTC, dongzl commented on pkg/runtime/optimize/dal/show_character_set.go
> +	"github.com/arana-db/arana/pkg/proto/rule"
Please format the import. use this tool:
```
go get -u github.com/dubbogo/tools/cmd/imports-formatter

imports-formatter
```

2022-09-03 08:45 UTC, dongzl commented on pkg/runtime/plan/dal/show_character_set.go
> +	"github.com/arana-db/arana/pkg/proto"
The same.

2022-09-03 13:54 UTC, jjeffcaii commented on pkg/runtime/ast/show.go
> +}
Delete this method, no need any more.

2022-09-03 13:55 UTC, jjeffcaii reviewed
Pls add UT.

2022-09-06 12:41 UTC, dongzl approved these changes

2022-09-11 04:34 UTC, jjeffcaii approved these changes

2022-09-11 04:34 UTC, merged