fix #393
arana-db/arana pull request #410
Opened 2022-09-14 08:24 UTC by robbinhan

**What this PR does**:

filter __arana prefix table name 

**Which issue(s) this PR fixes**:

Fixes #393

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-09-14 08:29 UTC, baerwang commented
use Provide filter, filter out uniformly arana core table

2022-09-14 13:55 UTC, dongzl requested changes

2022-09-14 13:55 UTC, dongzl commented on pkg/runtime/plan/dal/show_table_status.go
> +		return strings.HasPrefix(tableName, aranaSystemTablePrefix)
`aranaSystemTablePrefix`  is  a constant at the `show_tables` file, suggest define it to a common file.

2022-09-14 13:56 UTC, dongzl commented
> 

what is the `Provide filter`?

2022-09-18 02:54 UTC, dongzl commented
Close by #431

2022-09-18 02:54 UTC, closed without merging