feat: redefine object fields for arana-UI
arana-db/arana pull request #414
Opened 2022-09-17 14:30 UTC by GavinLam164

What this PR does:

redefine object fields for arana-UI

Which issue(s) this PR fixes:

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

2022-09-18 03:03 UTC, dongzl requested changes

2022-09-18 03:03 UTC, dongzl commented on pkg/admin/router/clusters.go
> +	"github.com/arana-db/arana/pkg/config"
please format import, use this tool:

```
go get -u github.com/dubbogo/tools/cmd/imports-formatter

imports-formatter
```

2022-09-18 03:03 UTC, dongzl commented on pkg/admin/router/db_groups.go
> +	"github.com/arana-db/arana/pkg/config"
The same.

2022-09-18 03:03 UTC, dongzl commented
Please fix CI, Thanks.

2022-09-18 04:03 UTC, jjeffcaii commented on pkg/admin/router/db_groups.go
> +	var res[] *config.Group
Should be `var res []*config.Group`

2022-09-18 04:04 UTC, jjeffcaii commented on pkg/boot/proto.go
> +	Name string                `yaml:"name" json:"name"`
format code

2022-09-18 04:04 UTC, jjeffcaii reviewed
pls fix

2022-09-24 15:16 UTC, jjeffcaii approved these changes

2022-09-24 15:30 UTC, dongzl approved these changes

2022-09-24 15:35 UTC, Lvnszn approved these changes

2022-09-24 15:36 UTC, merged

2022-09-24 15:37 UTC, Lvnszn commented on pkg/boot/proto.go
> +	Name   string                `yaml:"Name" json:"name"`
Name -> name