[WIP]Feat/add service registry
arana-db/arana pull request #431
Opened 2022-09-26 15:31 UTC by georgehao

**What this PR does**:
add registry

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-09-27 01:10 UTC, chuntaojun commented on pkg/boot/discovery.go
> +func (fp *discovery) ListServiceRegistry(ctx context.Context) *config.Registry {
ListServiceRegistry => GetServiceRegistry is better ?

2022-09-27 12:35 UTC, jjeffcaii commented on conf/bootstrap.yaml
> +      endpoints: "http://127.0.0.1:2379"
How about using existing config directly?

2022-11-10 03:31 UTC, dongzl requested changes

2022-11-10 03:31 UTC, dongzl commented on pkg/registry/store/etcdv3.go
> +	"github.com/arana-db/arana/pkg/util/log"
format import

2022-11-12 15:18 UTC, jjeffcaii approved these changes

2022-11-12 15:20 UTC, jjeffcaii commented on cmd/start/start.go
> +			log.Fatalf("create service registry failed: %v", err)
How about use ERR level? The `Fatalf` will cause process exiting, but here I think it's not necessary to let process killed.

2022-11-12 15:21 UTC, jjeffcaii commented on cmd/start/start.go
> +			log.Fatalf("do service register failed: %v", err)
Same as above.

2022-11-15 05:57 UTC, dongzl approved these changes

2022-11-15 11:59 UTC, chuntaojun approved these changes

2022-11-15 12:52 UTC, merged