feat:solo slow logger
arana-db/arana pull request #438
Opened 2022-10-02 10:29 UTC by baerwang

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-10-04 13:57 UTC, jjeffcaii commented on pkg/boot/boot.go
> +		namespace.UpdateSlowLogger(""),
What's the default slow log path? I think it should be read from bootstrap.yaml or an environment.

2022-10-04 13:57 UTC, jjeffcaii approved these changes

2022-10-07 05:49 UTC, dongzl requested changes

2022-10-07 05:49 UTC, dongzl commented on pkg/config/model.go
> +		APIVersion  string                 `yaml:"apiVersion" json:"apiVersion,omitempty"`
`yaml:"api_version" json:"api_version,omitempty"`  ??

2022-10-07 06:04 UTC, dongzl requested changes

2022-10-07 06:04 UTC, dongzl commented on conf/bootstrap.yaml
> +api_version: "1.0"
rollback it.

2022-10-07 06:12 UTC, dongzl approved these changes

2022-10-07 06:12 UTC, merged