feat: md5
arana-db/arana pull request #497
Opened 2022-11-07 13:31 UTC by baerwang

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #495 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-11-08 01:26 UTC, dongzl requested changes

2022-11-08 01:26 UTC, dongzl commented on pkg/runtime/function2/md5.go
> +const FuncMd5 = "CAST"
why `CAST`?

2022-11-08 02:23 UTC, jjeffcaii commented on pkg/runtime/function2/md5.go
> +	return fmt.Sprintf("%x", md5.Sum([]byte(fmt.Sprint(val)))), err
Here `val` maybe `*gxbig.Decimal`, must convert to string manually.

2022-11-08 09:18 UTC, dongzl approved these changes

2022-11-09 02:39 UTC, jjeffcaii approved these changes

2022-11-09 02:39 UTC, merged