[SQL] Support show replica status SQL statement. (arana#494)
arana-db/arana pull request #523
Opened 2022-11-16 13:56 UTC by DemanWei

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-11-17 07:11 UTC, dongzl requested changes

2022-11-17 07:11 UTC, dongzl commented on test/integration_test.go
> +	"github.com/arana-db/parser"
pls fix import format

```
go get -u github.com/dubbogo/tools/cmd/imports-formatter

imports-formatter
```

2022-11-17 12:37 UTC, jjeffcaii commented on test/integration_test.go
> +
reformat imports

2022-11-17 12:38 UTC, jjeffcaii approved these changes
LGTM

2022-11-18 07:57 UTC, dongzl approved these changes

2022-11-18 07:57 UTC, dongzl approved these changes

2022-11-18 08:00 UTC, merged