（WIP）feat:XA transaction basic shelf construction
arana-db/arana pull request #579
Opened 2022-12-23 09:25 UTC by chuntaojun

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-02-11 07:28 UTC, dongzl requested changes

2023-02-11 07:28 UTC, dongzl commented on pkg/runtime/transaction/trx_log.go
> +  ) ENGINE = InnoDB CHARSET = utf8
Suggest format the  sql content, and add comment for sql column

2023-02-11 07:28 UTC, dongzl commented on test/integration_test.go
> +		//WithDevMode(), // NOTICE: UNCOMMENT IF YOU WANT TO DEBUG LOCAL ARANA SERVER!!!
maybe need to keep the space

2023-02-11 07:41 UTC, dongzl approved these changes

2023-02-11 07:41 UTC, dongzl commented on integration_test/config/db/config.yaml
> +      sysDB:
we can discuss a suitable name.

2023-02-11 07:42 UTC, dongzl requested changes

2023-02-11 07:42 UTC, dongzl commented on pkg/runtime/transaction/trx_log.go
> +	delSql := `
Maybe defined as a string?

2023-02-11 08:51 UTC, maronghe commented
需要rebase一下吗

2023-02-12 12:09 UTC, jjeffcaii commented on integration_test/config/db/config.yaml
> +      sysDB:
How about underscore style `sys_db`?

2023-02-12 12:12 UTC, jjeffcaii commented on pkg/runtime/transaction/deadlock.go
> +	xd.cancel = cancel
Use `xd.ctx,xd.cancel = context.WithCancel(ctx)`  instead.

2023-02-12 12:13 UTC, jjeffcaii commented on pkg/runtime/transaction/hook.go
> +		Participants: []TrxParticipant{},
No need to initialize a slice.

2023-02-12 12:16 UTC, jjeffcaii commented on pkg/runtime/transaction/types.go
> +	NotEqual       dBOperation = "!="
I think it will be better to use `<>` instead.

2023-02-12 12:17 UTC, jjeffcaii reviewed
pls fix

2023-02-16 11:20 UTC, jjeffcaii approved these changes

2023-02-18 10:16 UTC, Mulavar approved these changes

2023-02-18 12:38 UTC, dongzl approved these changes

2023-02-18 12:38 UTC, merged