[Feature] Support HashJoin For Shards
arana-db/arana pull request #656
Opened 2023-03-19 15:17 UTC by huangwenkan9

目前支持简单的跨库hashjoin功能：
比如 `SELECT * FROM student JOIN salaries ON student.id = salaries.emp_on;`，其中student是分片表

持续迭代支持复杂的情况TODO：
- ~支持多个嵌套的复杂select sql查询；~
- 支持dateset上复杂的条件where或排序；
- 支持left/right join等sql；
- ...

涉及改动：
- `optimizeJoin()`支持跨库查；
- 新增`HashJoinPlan`；

2023-04-08 11:14 UTC, dongzl requested changes

2023-04-08 11:14 UTC, dongzl commented on pkg/runtime/plan/dml/hash_join.go
> +)
format import.

```
go get -u github.com/dubbogo/tools/cmd/imports-formatter

imports-formatter
```

2023-05-07 14:35 UTC, jjeffcaii commented on pkg/runtime/optimize/dml/select.go
> +	"github.com/arana-db/parser"
reformat imports

2023-05-07 14:43 UTC, jjeffcaii commented on pkg/runtime/optimize/dml/select.go
> +		stmtNode, err := p.ParseOneStmt(sb.String(), "", "")
1. Why restore the SQL here?
2. The original arguments index will be broken.

2023-05-07 14:44 UTC, jjeffcaii commented on pkg/runtime/plan/dml/hash_join.go
> +	// todo， 需要注意输出的列的顺序与join表的顺序
Translate to EN.

2023-05-07 14:46 UTC, jjeffcaii reviewed
It's a big PR, unit tests should be added. thx.

2023-07-06 14:53 UTC, closed without merging