add unit test for function (#708)
arana-db/arana pull request #733
Opened 2023-08-04 00:54 UTC by csynineyang

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-08-04 01:14 UTC, csynineyang commented
github.com/arana-db/arana/pkg/dataset/chain.go (100.0%)
github.com/arana-db/arana/pkg/dataset/filter.go (81.0%)
github.com/arana-db/arana/pkg/dataset/fuse.go (53.5%)
github.com/arana-db/arana/pkg/dataset/group_reduce.go (57.6%)
github.com/arana-db/arana/pkg/dataset/ordered.go (76.9%)
github.com/arana-db/arana/pkg/dataset/parallel.go (65.2%)
github.com/arana-db/arana/pkg/dataset/priority_queue.go (86.4%)
github.com/arana-db/arana/pkg/dataset/reduce.go (76.2%)
github.com/arana-db/arana/pkg/dataset/sort_merge_join.go (77.8%)
github.com/arana-db/arana/pkg/dataset/transform.go (72.2%)
github.com/arana-db/arana/pkg/dataset/virtual.go (100.0%)

2023-08-05 11:33 UTC, dongzl requested changes

2023-08-05 11:33 UTC, dongzl commented on pkg/dataset/reduce_test.go
> +)
Please format import, use this tool:
```
go get -u github.com/dubbogo/tools/cmd/imports-formatter

imports-formatter
```

2023-08-06 01:39 UTC, dongzl approved these changes

2023-08-06 02:01 UTC, Lvnszn approved these changes

2023-08-06 03:01 UTC, merged