Add unit test
arana-db/arana pull request #753
Opened 2023-08-25 03:29 UTC by dongzl

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-08-27 14:06 UTC, baerwang approved these changes

2023-08-27 14:06 UTC, baerwang commented on pkg/util/match/slice_match_test.go
> +// 测试 expected 和 actual 都为 nil 的情况
这里是不是要改成英语比较合适

2023-08-27 14:49 UTC, jjeffcaii requested changes
In short word, pls using testify lib instead.

2023-08-27 14:49 UTC, jjeffcaii commented on pkg/util/env/env_test.go
> +	os.Setenv(constants.EnvDevelopEnvironment, "1")
It will be better if reset the original env using defer when tests done.

2023-08-27 14:49 UTC, jjeffcaii commented on pkg/util/file/file_test.go
> +		t.Errorf("IsYaml(%s) = %v; want %v", path, result, expected)
use asserts.True instead.

2023-09-04 12:16 UTC, jjeffcaii approved these changes

2023-09-04 12:18 UTC, merged